{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-lifecycle",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.2.0.aar",
          "url": "camera-lifecycle-1.2.0.aar",
          "size": 20265,
          "sha512": "08e92529dd428f06578b4ac330c57662edf6b3af4fd1b09e0a8098d03b616d6e64ec4b810878deac1a1a04f6313655ae4439a379f8f3adc81f01837bde202291",
          "sha256": "8de55daf27a82de906608ae075397d5ac2ddc29ffd8734191c86f4a72cac79bc",
          "sha1": "905a07ac18795cfa38cd89283d0178747c46f179",
          "md5": "ff4cabdced1cd4a663347d5ea646ca49"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.2.0.aar",
          "url": "camera-lifecycle-1.2.0.aar",
          "size": 20265,
          "sha512": "08e92529dd428f06578b4ac330c57662edf6b3af4fd1b09e0a8098d03b616d6e64ec4b810878deac1a1a04f6313655ae4439a379f8f3adc81f01837bde202291",
          "sha256": "8de55daf27a82de906608ae075397d5ac2ddc29ffd8734191c86f4a72cac79bc",
          "sha1": "905a07ac18795cfa38cd89283d0178747c46f179",
          "md5": "ff4cabdced1cd4a663347d5ea646ca49"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-lifecycle-1.2.0-sources.jar",
          "url": "camera-lifecycle-1.2.0-sources.jar",
          "size": 17337,
          "sha512": "cf0398c7c6ec7515f6ed522c0d01e06605626f3301abd93f303b861c315b62b30b230addb81355219310e93212a51df6cf49f3a0d93b9af1b817cb9960e638c4",
          "sha256": "c5b07109d2e7fb4b0b362eaa1f5bea12c309a4eb6ca782274b59071dae2d879f",
          "sha1": "207884d7016947db3582f2bfc8f2073a390745ff",
          "md5": "b7b6068d83aba5939fd5ab2c5cac3e74"
        }
      ]
    }
  ]
}