{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-core",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "camera-core-1.2.0.aar",
          "url": "camera-core-1.2.0.aar",
          "size": 727145,
          "sha512": "e2d579ce6223737112463184f83c9d3573b029ffb98e9459681b98fe667962c2365a8901cf319bd79e4065cd1b07fba7fc6b0658b049c184a4c968949393db15",
          "sha256": "4eaa63a7c3793ac294a67ba0d173868d76ca2eecba41e765db8ae218028c0702",
          "sha1": "76fc2c8a2bd0abb9437e45a5b43635bc58bdca37",
          "md5": "14120010ba410fbabfeef6634c269e31"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "camera-core-1.2.0.aar",
          "url": "camera-core-1.2.0.aar",
          "size": 727145,
          "sha512": "e2d579ce6223737112463184f83c9d3573b029ffb98e9459681b98fe667962c2365a8901cf319bd79e4065cd1b07fba7fc6b0658b049c184a4c968949393db15",
          "sha256": "4eaa63a7c3793ac294a67ba0d173868d76ca2eecba41e765db8ae218028c0702",
          "sha1": "76fc2c8a2bd0abb9437e45a5b43635bc58bdca37",
          "md5": "14120010ba410fbabfeef6634c269e31"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-core-1.2.0-sources.jar",
          "url": "camera-core-1.2.0-sources.jar",
          "size": 543440,
          "sha512": "f248e6c56bb6cc32e967bc2e4cc3ca7eb428f3faeef3d4709da240b7af76c493328c39dd9f9cf5f5027e802e369dc5ee6b3aba1cd050e90fe8026cea0727941a",
          "sha256": "0e0e56cd2702f833b7876a0fea4caef67603e562302642d03acd3c6208b75deb",
          "sha1": "02490ea36e91aaa137d1a223f165bafcce48df18",
          "md5": "4a34724b85c11df12f8a66ac58b0a481"
        }
      ]
    }
  ]
}