{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-camera2",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.2.0.aar",
          "url": "camera-camera2-1.2.0.aar",
          "size": 383978,
          "sha512": "6bd8f8c667752e178a7eae751cfab37d727925ff542217801fb18f6825a4e3bfd202170e792581bc8cc141bf68dc114e7acfbc062384e621ada7e72b2fd848f2",
          "sha256": "162c306b824708a6d7ba24e97264d9289b6c697c42b313d5d61836af6009a4f2",
          "sha1": "e64d0efa5efeb4f8895f5bb3408dd09fdfe452db",
          "md5": "3829dcada03f336148ba940acf95155d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.2.0.aar",
          "url": "camera-camera2-1.2.0.aar",
          "size": 383978,
          "sha512": "6bd8f8c667752e178a7eae751cfab37d727925ff542217801fb18f6825a4e3bfd202170e792581bc8cc141bf68dc114e7acfbc062384e621ada7e72b2fd848f2",
          "sha256": "162c306b824708a6d7ba24e97264d9289b6c697c42b313d5d61836af6009a4f2",
          "sha1": "e64d0efa5efeb4f8895f5bb3408dd09fdfe452db",
          "md5": "3829dcada03f336148ba940acf95155d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-camera2-1.2.0-sources.jar",
          "url": "camera-camera2-1.2.0-sources.jar",
          "size": 302949,
          "sha512": "61709a0c50f20d07e42ab86e62adc66f063c071958533258fecd6581f9e54125cd1b8b1e20f9b3d1a1b1a6bafdae150b372f91ab901d6958695eb4f532845938",
          "sha256": "a84d85e0d2599eb6251db4de3ad78623e9ac903eb70b4911694f7804b7d32842",
          "sha1": "c5f159ee33da853e492543d4a42932fdec73e2aa",
          "md5": "c726cefd45982e63ae0f7d2d98c97d18"
        }
      ]
    }
  ]
}