{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-view",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-view-1.2.0.aar",
          "url": "camera-view-1.2.0.aar",
          "size": 90044,
          "sha512": "840a5436c49996d9c52c4fe71562677135715b39fdd2f5954450f85aec7badc57c84a1aac318746c5865fa12c54c810345fd63fd86f7468c0922e11007f57e0a",
          "sha256": "3aa90709eb15966b82359885250dc1dd024b810a941b6c7e045e5a721a0e4830",
          "sha1": "bd9bf659766fee9587074c50bd1bfeeb519a5525",
          "md5": "cce6cfb3b11af4c2e9513e57481fa477"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-view-1.2.0.aar",
          "url": "camera-view-1.2.0.aar",
          "size": 90044,
          "sha512": "840a5436c49996d9c52c4fe71562677135715b39fdd2f5954450f85aec7badc57c84a1aac318746c5865fa12c54c810345fd63fd86f7468c0922e11007f57e0a",
          "sha256": "3aa90709eb15966b82359885250dc1dd024b810a941b6c7e045e5a721a0e4830",
          "sha1": "bd9bf659766fee9587074c50bd1bfeeb519a5525",
          "md5": "cce6cfb3b11af4c2e9513e57481fa477"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-view-1.2.0-sources.jar",
          "url": "camera-view-1.2.0-sources.jar",
          "size": 70874,
          "sha512": "4f5f4e8aa9c931f1f85d8dfd6aa6c065cd8981a9081eee10ef768468c12ba5f7e4725ec5c49049db32d9e8aefe257e447f985a71320eb82f5ac2c2b0b0fd5d29",
          "sha256": "7569a0b66d8c3fa8a4c08faf4983be84db499802bf7b27eaf112479c8cd8b721",
          "sha1": "9e704afef8cc2ad3f57a13fa7b35b2991f48499c",
          "md5": "dc81a75ad1a46b2227e4cc3888798d06"
        }
      ]
    }
  ]
}